_commit: 8ecad33
_src_path: gh:monarch-initiative/cookiecutter-monarch-ingest
copyright_year: '2026'
email: info@monarchinitiative.org
full_name: Monarch Initiative
github_handle: monarch-initiative
github_org: monarch-initiative
license: BSD-3-Clause
project_description: Xenbase gene to phenotype and orthology ingests
project_name: xenbase-ingest
project_slug: xenbase_ingest
